### ISSUE TITLE
Read Permissions like Samba Share Addon needed

### ISSUE THREAD

**Issue by panhans** [adrianoamalfi/hassos-addons#7]
Hi there,

first, thank you for the Addon! I've run duplicati using portainer for backup my nextcloud files.
Now I tried your addon and it cant access the nextcloud directory in share. The samba addon did it and my selfhostet instance, too.

Here is my portainer start script. Don't know if it helps. Maybe the configuration of the samba share addon is able to help, too.

```
version: "2.1"
services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=911
      - PGID=1001
      - TZ=Europe/Berlin
      - CLI_ARGS= #optional
    volumes:
      - /mnt/data/supervisor/config/duplicati:/config
      - /mnt/data/supervisor/backup/duplicati:/backups
      - /mnt/data/supervisor/share/:/source
    ports:
      - 8200:8200
    restart: unless-stopped
```
